/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec.sokalau;

public class App {
    public static void main(String[] args) {
        System.out.println(Utils.isAllPositiveNumbers("12", "79"));
    }
}
