/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec.sokalau;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {
    @Test
    public void isPositiveNumberTrue() {
        assertTrue(StringUtils.isPositiveNumber("21"));
    }

    @Test
    public void isPositiveNumberFalse() {
        assertFalse(StringUtils.isPositiveNumber("-21"));
    }

    @Test
    public void isPositiveNumberZero() {
        assertFalse(StringUtils.isPositiveNumber("0"));
    }
}
